//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalisisCodigoEntities : DbContext
    {
        public AnalisisCodigoEntities()
            : base("name=AnalisisCodigoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<R2PBClase> R2PBClase { get; set; }
        public virtual DbSet<R2PBControl> R2PBControl { get; set; }
        public virtual DbSet<R2PBHerencia> R2PBHerencia { get; set; }
        public virtual DbSet<R2PBMetodo> R2PBMetodo { get; set; }
        public virtual DbSet<R2PBPaquete> R2PBPaquete { get; set; }
        public virtual DbSet<R2PBParametro> R2PBParametro { get; set; }
        public virtual DbSet<R2PBParametroModificador> R2PBParametroModificador { get; set; }
        public virtual DbSet<R2PBPropiedad> R2PBPropiedad { get; set; }
        public virtual DbSet<R2PBProyecto> R2PBProyecto { get; set; }
        public virtual DbSet<R2PBUsing> R2PBUsing { get; set; }
        public virtual DbSet<R2PBBitacora> R2PBBitacora { get; set; }
        public virtual DbSet<R2PBRepositorio> R2PBRepositorio { get; set; }
    }
}
