//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBMetodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R2PBMetodo()
        {
            this.R2PBControl = new HashSet<R2PBControl>();
            this.R2PBParametro = new HashSet<R2PBParametro>();
        }
    
        public int IdMetodo { get; set; }
        public int IdClase { get; set; }
        public string Visibilidad { get; set; }
        public string Nombre { get; set; }
        public string Retorno { get; set; }
        public int IdProyecto { get; set; }
        public int IdPaquete { get; set; }
        public int LineaComienzo { get; set; }
        public int LineaFinal { get; set; }
    
        public virtual R2PBClase R2PBClase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBControl> R2PBControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBParametro> R2PBParametro { get; set; }
    }
}
