//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R2PBProyecto()
        {
            this.R2PBClase = new HashSet<R2PBClase>();
        }
    
        public int IdProyecto { get; set; }
        public int IdPaquete { get; set; }
        public string NombreProyecto { get; set; }
        public string Lenguaje { get; set; }
        public string IdentificadorProyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBClase> R2PBClase { get; set; }
        public virtual R2PBPaquete R2PBPaquete { get; set; }
    }
}
