//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBClase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R2PBClase()
        {
            this.R2PBHerencia = new HashSet<R2PBHerencia>();
            this.R2PBMetodo = new HashSet<R2PBMetodo>();
            this.R2PBPropiedad = new HashSet<R2PBPropiedad>();
            this.R2PBUsing = new HashSet<R2PBUsing>();
        }
    
        public int IdClase { get; set; }
        public int IdProyecto { get; set; }
        public string Visibilidad { get; set; }
        public string Nombre { get; set; }
        public short Tipo { get; set; }
        public string NameSpace { get; set; }
        public int IdPaquete { get; set; }
        public int LineaComienzo { get; set; }
        public int LineaFinal { get; set; }
    
        public virtual R2PBProyecto R2PBProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBHerencia> R2PBHerencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBMetodo> R2PBMetodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBPropiedad> R2PBPropiedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBUsing> R2PBUsing { get; set; }
    }
}
