//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBPaquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R2PBPaquete()
        {
            this.R2PBProyecto = new HashSet<R2PBProyecto>();
        }
    
        public int IdPaquete { get; set; }
        public string NombrePaquete { get; set; }
        public string IdentificadorPaquete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R2PBProyecto> R2PBProyecto { get; set; }
    }
}
