//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBRepositorio
    {
        public int IdRepositorio { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public int Dia { get; set; }
        public int Hora { get; set; }
        public int Segundo { get; set; }
        public int Minuto { get; set; }
        public System.DateTime FechaCompleta { get; set; }
        public string Hash { get; set; }
        public string NombreRepositorio { get; set; }
        public string NombreAutorRepositorio { get; set; }
        public string AutorCommit { get; set; }
    }
}
