//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBControl
    {
        public int IdControl { get; set; }
        public int IdMetodo { get; set; }
        public string Nombre { get; set; }
        public int Tipo { get; set; }
        public int LineaComienzo { get; set; }
        public int LineaFinal { get; set; }
        public int IdProyecto { get; set; }
        public int IdPaquete { get; set; }
        public int IdClase { get; set; }
    
        public virtual R2PBMetodo R2PBMetodo { get; set; }
    }
}
