//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2PB.AnalisisCodigo.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class R2PBBitacora
    {
        public int IdBitacora { get; set; }
        public string IdSolucion { get; set; }
        public string StackTrace { get; set; }
        public string Mensaje { get; set; }
        public int Componente { get; set; }
        public string InformacionExepcion { get; set; }
    }
}
